### PR TITLE
subtitles to the main screen in nds encodes

### PR DESCRIPTION
**Pull request by Stovent**

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
What's up? It doesn't work with TASVideos/TASEncodingPackage?

**Comment by vadosnaprimer** [comment]
Why not TASVideos/TASEncodingPackage? My fork has issue tracker, but the code is all sent to that one instead. When all issues are resolved, I might delete my repo, making TASVideos/TASEncodingPackage primary.

**Comment by Stovent** [comment]
Probably miss click, I redo it with TASVideos. Also, should I add it to master and x86 too ?

**Comment by vadosnaprimer** [comment]
No, these other 2 aren't important anymore. If necessary, I'll cherrypick your commit to there.

**Pull request closed without merging**
